server:
  port: ${PORT:8107}

spring:
  application:
    name: analytics-service
  config:
    import: classpath:aiguruz-common.yml
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/aiguruz_analytics}
